name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          clang-format \
          python3.12 \
          python3.12-dev \
          python3.12-venv \
          python3.12-distutils
        python3.12 -m ensurepip
        python3.12 -m pip install --upgrade pip
        python3.12 -m pip install conan poetry

    - name: Run Makefile Targets (Install + Build)
      run: |
        make install
        make build

    - name: Run C++ Tests
      run: |
        make cpptest
