name: C++ Test and Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          clang-format \
          python3.12 \
          python3.12-dev \
          python3.12-venv
        python3.12 -m pip install --user conan

    - name: Configure Conan Profile
      run: |
        conan profile detect
        conan install . --build=missing

    - name: Build Project with CMake
      run: |
        mkdir -p build
        cd build
        cmake -G Ninja ..
        ninja

    - name: Run C++ Tests with Make
      run: |
        cd build
        make test

    - name: Run Clang-Format (C++ Formatter)
      run: |
        find . -name "*.cpp" -o -name "*.h" | xargs clang-format -i

