name: CI - C++ Linting and Formatting

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    cpp-lint-and-format:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        
        - name: Install Dependencies
          run: |
            make dependencies

        - name: Run Clang-Tidy and Clang-Format (Linters)
          run: |
            make cpplint
            make cppformat