name: C++ Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy clang-format cmake ninja-build build-essential

    - name: Build Project and Generate Compile Commands
      run: |
        make build

    - name: Run Clang-Tidy and Clang-Format
      run: |
        make cpplint
        make cppformat
