name: C++ Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          curl -L https://github.com/conan-io/conan/releases/download/2.0.0/conan-2.0.0-linux.zip -o conan.zip
          unzip conan.zip -d ~/.local/bin
          export PATH=$HOME/.local/bin:$PATH
          conan profile detect
          pip install ninja  # Install Ninja build system locally

      - name: Install Build Requirements
        run: |
          conan install . --build=missing

      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja

      - name: Run Tests
        run: |
          cd build
          ctest

