name: CI - C++ Unit Tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    cpp-unit-tests:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Run C++ Build
          run: make build
        
        - name: Run C++ Tests
          run: make cpptest
