name: Python Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build clang

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry conan

    - name: Install Dependencies
      run: |
        make install

    - name: Build the Project
      run: |
        make build

    - name: Run Python and C++ Tests
      run: |
        make test
