name: Python Test and Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry mypy ruff

    - name: Run Ruff (Python Linter)
      run: ruff .

    - name: Run Mypy (Type Checker)
      run: mypy .

    - name: Install Dependencies with Poetry
      run: poetry install

    - name: Run Pytest (Python Tests)
      run: poetry run pytest

