name: Python Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python 3.12 and Poetry
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.12 python3.12-dev python3.12-venv
        python3.12 -m ensurepip
        python3.12 -m pip install --upgrade pip
        python3.12 -m pip install poetry

    - name: Run Python Linters
      run: |
        make pylint
