name: Python Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install Dependencies
      run: |
        make install

    - name: Run Linters
      run: |
        make lint
